---
version: "3.1"
services:
  google-home-voicetext-firebase:
    image: vet5lqplpecmpnqb/google-home-voicetext-firebase
    networks:
      - bridge
    env_file:
      - .env
    volumes:
      - ${PWD}/serviceAccountKey.json:${FIREBASE_CREDENTIAL}:ro
    deploy:
      restart_policy:
        condition: on-failure

networks:
  bridge: